In [8]:
#Applying Operations to Elements

import numpy as np
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#create functions that adds 100 to somethings
add_100 = lambda i:i+100

#create vectorized function
vectorized= np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [11]:
# Finding the Maximum and Minimum Values

import numpy as np
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(np.max(matrix))
print(np.min(matrix))

# Find maximum element in each column
print(np.max(matrix, axis=0))

# Find maximum element in each row
print(np.max(matrix, axis=1))

9
1
[7 8 9]
[3 6 9]


In [15]:
# Calculating the Average, Variance, and Standard Deviation

import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

5.0
6.666666666666667
2.581988897471611


In [21]:
#Reshaping Arrays

import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

#Reshape matrix into 2*6 matrix
print(matrix.reshape(2,6))
print(matrix.reshape(12))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
# Transposing a Vector or Matrix

import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix.T)
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
