In [3]:
#Creating a vector

import numpy as np
vec_row=np.array([1,2,3])
vec_col=np.array([[1],
                 [2],
                 [3]])
print(vec_row)
print(vec_col)

[1 2 3]
[[1]
 [2]
 [3]]


In [4]:
#Creating a matrix

import numpy as np
matrix=np.array([[1,2],
                 [1,2],
                  [1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [6]:
#Creating a Sparse matrix

import numpy as np
from scipy import sparse
matrix=np.array([[0,0],
                 [0,1],
                 [3,0]])
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [20]:
# Selecting Elements

import numpy as np

# Use np.array for 1D vectors
vector = np.array([1,2,3,4,5,6]) 
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Now these work correctly:
print(vector[2])    # Output: 3
print(matrix[1,1])  # Output: 5
print(vector[:])
print(vector[3:])
print(vector[-1])
print(matrix[:2,:])

3
5
[1 2 3 4 5 6]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]


In [24]:
#Describing a matrix

import numpy as np
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 4)
12
2
