In [3]:
#Finding the Rank of a Matrix

import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

np.int64(2)

In [5]:
#Calculating the Determinant

import numpy as np

matrix=np.array([[1,2,3],
                 [2,4,6],
                 [3,8,9]])
# Return determinant of matrix
np.linalg.det(matrix)

np.float64(0.0)

In [6]:
#Getting the Diagonal of a Matrix

import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [3,8,9]])

matrix.diagonal()

array([1, 5, 9])

In [10]:
# Calculating the Trace of a Matrix
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix.trace()

# Return diagonal and sum elements
print(sum(matrix.diagonal()))

15


In [12]:
#Finding Eigenvalues and Eigenvectors

import numpy as np

matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]
